/**
 * Utility for generating mock embeddings for demo data
 * In production, these would be generated by OpenAI or similar service
 */

/**
 * Generate a mock embedding vector (1536 dimensions for OpenAI text-embedding-ada-002)
 * For demo purposes, we create embeddings that have some semantic clustering
 * based on the input text hash
 */
export function generateMockEmbedding(text: string): number[] {
  const dimensions = 1536;
  const embedding: number[] = new Array(dimensions);

  // Use simple hash of text to seed the randomness for consistency
  let hash = 0;
  for (let i = 0; i < text.length; i++) {
    hash = (hash << 5) - hash + text.charCodeAt(i);
    hash = hash & hash;
  }

  // Initialize seeded random
  const seededRandom = (() => {
    let seed = Math.abs(hash);
    return () => {
      seed = (seed * 9301 + 49297) % 233280;
      return seed / 233280;
    };
  })();

  // Generate normalized random vector
  let magnitude = 0;
  for (let i = 0; i < dimensions; i++) {
    embedding[i] = (seededRandom() - 0.5) * 2;
    magnitude += embedding[i] * embedding[i];
  }

  // Normalize to unit vector (as real embeddings are)
  magnitude = Math.sqrt(magnitude);
  for (let i = 0; i < dimensions; i++) {
    embedding[i] = embedding[i] / magnitude;
  }

  return embedding;
}

/**
 * Format embedding as PostgreSQL array string
 */
export function formatEmbeddingForPostgres(embedding: number[]): string {
  return `[${embedding.join(',')}]`;
}

/**
 * Generate embedding from business data
 */
export function generateBusinessEmbedding(business: {
  name: string;
  description?: string;
  industry: string;
  sub_industry?: string;
  specialties?: string[];
  city?: string;
  state?: string;
}): number[] {
  const textParts = [
    business.name,
    business.description || '',
    business.industry,
    business.sub_industry || '',
    ...(business.specialties || []),
    business.city || '',
    business.state || '',
  ];

  const embeddingText = textParts.filter(Boolean).join(' ');
  return generateMockEmbedding(embeddingText);
}
