/**
 * Industry definitions for diverse demo data
 */

export const INDUSTRIES = {
  DENTAL: {
    name: 'Dental Services',
    subIndustries: [
      'General Dentistry',
      'Orthodontics',
      'Pediatric Dentistry',
      'Cosmetic Dentistry',
      'Oral Surgery',
      'Endodontics',
      'Periodontics',
      'Prosthodontics',
    ],
    specialties: [
      'Teeth Whitening',
      'Dental Implants',
      'Root Canal',
      'Invisalign',
      'Veneers',
      'Crowns and Bridges',
      'TMJ Treatment',
      'Sleep Apnea Treatment',
    ],
    certifications: ['ADA Certified', 'Board Certified', 'CEREC Certified', 'Invisalign Provider'],
    businessTypes: ['Private Practice', 'Group Practice', 'DSO', 'Mobile Dental'],
  },
  HVAC: {
    name: 'HVAC Services',
    subIndustries: [
      'Residential HVAC',
      'Commercial HVAC',
      'Industrial HVAC',
      'HVAC Installation',
      'HVAC Repair',
      'HVAC Maintenance',
      'Duct Cleaning',
      'Indoor Air Quality',
    ],
    specialties: [
      'Heat Pump Installation',
      'Central AC',
      'Ductless Mini-Split',
      'Furnace Repair',
      'Boiler Service',
      'Smart Thermostat Installation',
      'Energy Audits',
      'Refrigeration',
    ],
    certifications: ['NATE Certified', 'EPA Certified', 'HVAC Excellence', 'LEED Certified'],
    businessTypes: ['Owner-Operated', 'Franchise', 'Regional Chain', 'National Chain'],
  },
  TRUCKING: {
    name: 'Trucking & Logistics',
    subIndustries: [
      'Long Haul Trucking',
      'Regional Trucking',
      'Local Delivery',
      'Freight Brokerage',
      'Intermodal',
      'Refrigerated Transport',
      'Flatbed Trucking',
      'Tanker Transport',
    ],
    specialties: [
      'Hazmat Transport',
      'Oversized Loads',
      'Expedited Shipping',
      'Less-Than-Truckload',
      'Full Truckload',
      'Cross-Border',
      'White Glove Service',
      'Last Mile Delivery',
    ],
    certifications: [
      'DOT Certified',
      'FMCSA Approved',
      'Hazmat Certified',
      'SmartWay Certified',
    ],
    businessTypes: ['Owner-Operator', 'Small Fleet', 'Regional Carrier', 'National Carrier'],
  },
  PLUMBING: {
    name: 'Plumbing Services',
    subIndustries: [
      'Residential Plumbing',
      'Commercial Plumbing',
      'Emergency Plumbing',
      'Drain Cleaning',
      'Water Heater Service',
      'Sewer Line Repair',
      'Repiping',
      'Backflow Prevention',
    ],
    specialties: [
      'Trenchless Sewer Repair',
      'Hydro Jetting',
      'Leak Detection',
      'Water Treatment',
      'Gas Line Installation',
      'Bathroom Remodeling',
      'Kitchen Plumbing',
      'Septic Systems',
    ],
    certifications: ['Master Plumber', 'Journeyman Plumber', 'Backflow Certified', 'Green Plumber'],
    businessTypes: ['Independent', 'Franchise', 'Family Business', 'Multi-Location'],
  },
  ROOFING: {
    name: 'Roofing Services',
    subIndustries: [
      'Residential Roofing',
      'Commercial Roofing',
      'Roof Repair',
      'Roof Replacement',
      'Roof Inspection',
      'Gutter Installation',
      'Skylight Installation',
      'Green Roofing',
    ],
    specialties: [
      'Asphalt Shingles',
      'Metal Roofing',
      'Tile Roofing',
      'Flat Roofing',
      'TPO/EPDM',
      'Storm Damage Repair',
      'Solar Panel Installation',
      'Roof Coating',
    ],
    certifications: [
      'GAF Master Elite',
      'CertainTeed SELECT',
      'OSHA Certified',
      'Haag Certified Inspector',
    ],
    businessTypes: ['Local Contractor', 'Regional Company', 'Storm Restoration', 'Manufacturer-Backed'],
  },
  LANDSCAPING: {
    name: 'Landscaping Services',
    subIndustries: [
      'Lawn Care',
      'Landscape Design',
      'Hardscaping',
      'Tree Service',
      'Irrigation',
      'Snow Removal',
      'Landscape Maintenance',
      'Outdoor Lighting',
    ],
    specialties: [
      'Organic Lawn Care',
      'Xeriscaping',
      'Retaining Walls',
      'Patios and Decks',
      'Water Features',
      'Mosquito Control',
      'Seasonal Cleanup',
      'Commercial Grounds',
    ],
    certifications: [
      'Certified Arborist',
      'Landscape Industry Certified',
      'Pesticide Applicator License',
      'Irrigation Association Certified',
    ],
    businessTypes: ['Sole Proprietor', 'Crew-Based', 'Full-Service', 'Specialty Provider'],
  },
  REAL_ESTATE: {
    name: 'Real Estate',
    subIndustries: [
      'Residential Sales',
      'Commercial Sales',
      'Property Management',
      'Real Estate Investment',
      'Leasing',
      'Appraisal',
      'Real Estate Development',
      'Real Estate Consulting',
    ],
    specialties: [
      'Luxury Homes',
      'First-Time Buyers',
      'Investment Properties',
      'Vacation Rentals',
      'Multi-Family',
      'Office Space',
      'Retail Properties',
      'Industrial Properties',
    ],
    certifications: ['Licensed Realtor', 'Broker', 'CRS', 'ABR', 'GRI'],
    businessTypes: ['Independent Agent', 'Brokerage', 'Team', 'National Franchise'],
  },
  LEGAL: {
    name: 'Legal Services',
    subIndustries: [
      'Personal Injury',
      'Family Law',
      'Criminal Defense',
      'Estate Planning',
      'Business Law',
      'Real Estate Law',
      'Immigration Law',
      'Bankruptcy Law',
    ],
    specialties: [
      'Car Accidents',
      'Divorce',
      'DUI Defense',
      'Wills and Trusts',
      'Contract Law',
      'Employment Law',
      'Intellectual Property',
      'Tax Law',
    ],
    certifications: ['Bar Certified', 'Board Certified Specialist', 'AV Rated', 'Super Lawyers'],
    businessTypes: ['Solo Practice', 'Small Firm', 'Mid-Size Firm', 'Large Firm'],
  },
  MEDICAL: {
    name: 'Medical Services',
    subIndustries: [
      'Primary Care',
      'Urgent Care',
      'Specialty Care',
      'Surgery',
      'Diagnostic Imaging',
      'Physical Therapy',
      'Mental Health',
      'Home Health',
    ],
    specialties: [
      'Cardiology',
      'Orthopedics',
      'Dermatology',
      'Pediatrics',
      'OB/GYN',
      'Geriatrics',
      'Sports Medicine',
      'Pain Management',
    ],
    certifications: ['Board Certified', 'JCAHO Accredited', 'Medicare Certified', 'Specialty Board'],
    businessTypes: ['Private Practice', 'Group Practice', 'Hospital-Affiliated', 'Clinic'],
  },
  AUTOMOTIVE: {
    name: 'Automotive Services',
    subIndustries: [
      'Auto Repair',
      'Auto Body',
      'Oil Change',
      'Tire Service',
      'Transmission Repair',
      'Brake Service',
      'Detailing',
      'Towing',
    ],
    specialties: [
      'European Cars',
      'Luxury Vehicles',
      'Diesel Repair',
      'Hybrid/Electric',
      'Classic Cars',
      'Performance Tuning',
      'Fleet Service',
      'Mobile Repair',
    ],
    certifications: ['ASE Certified', 'I-CAR Certified', 'AAA Approved', 'Manufacturer Certified'],
    businessTypes: ['Independent Shop', 'Chain', 'Dealership', 'Mobile Service'],
  },
} as const;

export type IndustryKey = keyof typeof INDUSTRIES;

export const INDUSTRY_KEYS = Object.keys(INDUSTRIES) as IndustryKey[];

export function getRandomIndustry(): IndustryKey {
  return INDUSTRY_KEYS[Math.floor(Math.random() * INDUSTRY_KEYS.length)];
}
