packages:
  - 'apps/*'
  - 'packages/*'

catalogs:
  default:
    react: '18.2.0'
    react-dom: '18.2.0'
    next: '15.0.3'
    typescript: '5.4.5'
    '@nestjs/common': '10.3.10'
    '@nestjs/core': '10.3.10'
    '@nestjs/platform-fastify': '10.3.10'
