import { NextRequest, NextResponse } from 'next/server';

export async function POST(request: NextRequest) {
  try {
    const { prospectIds } = await request.json();

    if (!prospectIds || !Array.isArray(prospectIds)) {
      return NextResponse.json(
        { error: 'Invalid prospect IDs' },
        { status: 400 }
      );
    }

    // Simulate AI processing delay
    await new Promise(resolve => setTimeout(resolve, 1000));

    // Mock AI summary content
    const mockSummary = `# AI-Generated Prospect Summary

## Overview
Based on the analysis of ${prospectIds.length} selected prospects, here are the key insights:

## Key Findings
- **Total Revenue Potential**: $${(Math.random() * 10000000).toFixed(0).replace(/\B(?=(\d{3})+(?!\d))/g, ",")}
- **Geographic Distribution**: Primarily concentrated in tech hubs
- **Industry Focus**: Software and technology companies dominate
- **Growth Indicators**: Strong hiring trends and funding activity

## Recommended Approach
1. **Priority Targeting**: Focus on companies with 50-200 employees
2. **Personalization**: Leverage recent funding announcements
3. **Timing**: Q4 budget planning season presents optimal opportunity

## Next Steps
- Develop personalized outreach sequences
- Research key decision makers
- Prepare tailored value propositions
- Set up tracking and follow-up system

---
*This summary was generated by AI based on available data. Verify key insights before taking action.*`;

    // Create a streaming response
    const encoder = new TextEncoder();
    const stream = new ReadableStream({
      async start(controller) {
        try {
          // Simulate streaming by sending chunks
          const chunks = mockSummary.split('\n');
          
          for (let i = 0; i < chunks.length; i++) {
            const chunk = chunks[i] + (i < chunks.length - 1 ? '\n' : '');
            
            controller.enqueue(
              encoder.encode(`data: ${JSON.stringify({ content: chunk })}\n\n`)
            );
            
            // Small delay to simulate streaming
            await new Promise(resolve => setTimeout(resolve, 50));
          }
          
          // Send completion signal
          controller.enqueue(encoder.encode('data: [DONE]\n\n'));
          controller.close();
        } catch (error) {
          controller.error(error);
        }
      },
    });

    return new Response(stream, {
      headers: {
        'Content-Type': 'text/plain; charset=utf-8',
        'Cache-Control': 'no-cache',
        'Connection': 'keep-alive',
      },
    });

  } catch (error) {
    console.error('AI Summary API Error:', error);
    return NextResponse.json(
      { error: 'Failed to generate AI summary' },
      { status: 500 }
    );
  }
}