import { Organization, User } from "@/types";

export const mockOrganizations: Organization[] = [
  {
    id: "org_1",
    name: "Acme Corporation",
    status: "active",
    plan: "enterprise",
    usage: {
      users: 150,
      requests: 45000,
      storage: 850,
    },
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-11-20"),
  },
  {
    id: "org_2",
    name: "TechStart Inc",
    status: "active",
    plan: "pro",
    usage: {
      users: 45,
      requests: 12000,
      storage: 250,
    },
    createdAt: new Date("2024-03-22"),
    updatedAt: new Date("2024-11-19"),
  },
  {
    id: "org_3",
    name: "Global Services Ltd",
    status: "suspended",
    plan: "pro",
    usage: {
      users: 78,
      requests: 28000,
      storage: 520,
    },
    createdAt: new Date("2024-02-10"),
    updatedAt: new Date("2024-11-10"),
  },
  {
    id: "org_4",
    name: "Innovation Labs",
    status: "active",
    plan: "free",
    usage: {
      users: 12,
      requests: 2500,
      storage: 50,
    },
    createdAt: new Date("2024-06-05"),
    updatedAt: new Date("2024-11-18"),
  },
];

export const mockUsers: User[] = [
  {
    id: "user_1",
    organizationId: "org_1",
    email: "john.doe@acme.com",
    name: "John Doe",
    role: "admin",
    lastActivity: new Date("2024-11-20T10:30:00"),
    connectorsEnabled: ["crm", "email", "calendar"],
    mfaEnabled: true,
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-11-20"),
  },
  {
    id: "user_2",
    organizationId: "org_1",
    email: "jane.smith@acme.com",
    name: "Jane Smith",
    role: "member",
    lastActivity: new Date("2024-11-19T15:45:00"),
    connectorsEnabled: ["crm", "email"],
    mfaEnabled: true,
    createdAt: new Date("2024-02-15"),
    updatedAt: new Date("2024-11-19"),
  },
  {
    id: "user_3",
    organizationId: "org_2",
    email: "bob.wilson@techstart.com",
    name: "Bob Wilson",
    role: "admin",
    lastActivity: new Date("2024-11-20T08:15:00"),
    connectorsEnabled: ["crm"],
    mfaEnabled: false,
    createdAt: new Date("2024-03-25"),
    updatedAt: new Date("2024-11-20"),
  },
  {
    id: "user_4",
    organizationId: "org_3",
    email: "alice.johnson@global.com",
    name: "Alice Johnson",
    role: "member",
    lastActivity: new Date("2024-11-15T12:00:00"),
    connectorsEnabled: ["crm", "calendar"],
    mfaEnabled: true,
    createdAt: new Date("2024-02-20"),
    updatedAt: new Date("2024-11-15"),
  },
];
